### ISSUE TITLE
NPM errors

### ISSUE THREAD

**Issue by meatbroc** [NoSkill33/DiscordJS-Bot-Template#1]
Running npm install eventually starts spamming errors and when I try node bootstrap.js it says I'm missing discord.js.
![Screenshot (2)](https://github.com/user-attachments/assets/65a9180f-e515-454d-89b3-54f52f22ffd1)

**Comment by october37** [comment]
Please send me the log file, and make sure to send it from; C:\Users\<yourname>\AppData\Local\npm-cache\_logs\
Thank you!

**Comment by october37** [comment]
The issue has been resolved. **Please try cloning the repository again** and running npm install. Let me know if you encounter any further problems!

**Comment by meatbroc** [comment]
I no longer need the template, but thanks for working on it!
